import {useEffect,useRef,useState} from 'react';
import {Capacitor} from '@capacitor/core';
import {capturePhoto} from './native';
import {apiFetch} from './lib/api';
import {toast} from 'sonner';
export default function PhotoCapture({demo}:{demo:boolean}){
 const [draft,setDraft]=useState<{id:string,blob:Blob}|null>(null),[preview,setPreview]=useState(''),[sharing,setSharing]=useState('private'),[text,setText]=useState(''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!draft){setPreview('');return}const u=URL.createObjectURL(draft.blob);setPreview(u);return()=>URL.revokeObjectURL(u)},[draft]);
 async function choose(file:File){if(file.size>20*1024*1024){toast.error('Elegí una foto de hasta 20 MB.');return}setBusy(true);const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(),'image/jpeg',.85));setDraft({id:crypto.randomUUID(),blob})}catch{toast.error('No se pudo leer la foto.')}finally{URL.revokeObjectURL(url);setBusy(false)}}
 async function take(){if(!Capacitor.isNativePlatform()){input.current?.click();return}setBusy(true);try{setDraft({id:crypto.randomUUID(),blob:await capturePhoto()})}catch{toast.error('No se tomó la foto. Revisá el permiso de cámara.')}finally{setBusy(false)}}
 async function save(){if(!draft)return;if(demo){toast.info('Foto de demostración: no se subió ni se compartió.');return}setBusy(true);try{const r=await apiFetch(`/api/photos?id=${draft.id}&sharing=${sharing}&text=${encodeURIComponent(text)}`,{method:'POST',headers:{'Content-Type':'image/jpeg'},body:draft.blob,signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error((await r.json()).error);toast.success('Foto guardada. Podés verla en Mi teléfono.');setDraft(null)}catch(e){toast.error((e instanceof Error?e.message:'No se guardó.')+' Conservamos la foto en esta pantalla para reintentar.')}finally{setBusy(false)}}
 return <><p>Tomá una foto visible y elegí quién podrá verla. Solo se sube cuando confirmás Guardar.</p><input ref={input} type="file" accept="image/*" capture="environment" className="sr-only" onChange={e=>{if(e.target.files?.[0])choose(e.target.files[0]);e.target.value=''}}/>{preview&&<img src={preview} className="native-photo" alt="Foto pendiente de guardar"/>}<label className="field">Descripción<textarea maxLength={1000} value={text} onChange={e=>setText(e.target.value)}/></label><label className="field">Compartir<select value={sharing} onChange={e=>setSharing(e.target.value)}><option value="private">Solo yo</option><option value="now">Mi círculo, desde ahora</option><option value="sos">Mi círculo, al confirmar un SOS</option></select></label><button className="button outline wide" disabled={busy} onClick={take}>Tomar o elegir foto</button>{draft&&<button className="button primary wide" disabled={busy} onClick={save}>{busy?'Guardando…':'Guardar foto'}</button>}<small>Sin reconocimiento de personas ni captura oculta. Cerrar esta pantalla descarta una foto sin guardar.</small></>
}
