import {useEffect,useRef,useState} from 'react';
import {Mic,Phone,ShieldCheck,Volume2,Wallet,Camera,UserRoundPlus,BookUser} from 'lucide-react';
import {nextSosTap} from '../shared/contact-actions';
export function SosButton({onActivate,compact=false,disabled=false}:{onActivate:()=>void,compact?:boolean,disabled?:boolean}){
 const last=useRef<number|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),lock=useRef(false),[armed,setArmed]=useState(false);
 function reset(){last.current=null;setArmed(false);if(timer.current)clearTimeout(timer.current)}
 useEffect(()=>{const clear=()=>{reset();lock.current=false};window.addEventListener('blur',clear);return()=>{if(timer.current)clearTimeout(timer.current);window.removeEventListener('blur',clear)}},[]);
 function tap(){if(disabled||lock.current)return;const next=nextSosTap(last.current,Date.now());last.current=next.at;if(next.activate){reset();lock.current=true;onActivate();timer.current=setTimeout(()=>{lock.current=false},1500)}else{setArmed(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(reset,1200)}}
 return <button type="button" className={'emergency-trigger '+(compact?'compact ':'')+(armed?'armed':'')} disabled={disabled} onClick={tap} aria-label="SOS auxilio. Tocá dos veces para iniciar el aviso con cinco segundos para cancelar."><strong>SOS</strong><span>{armed?'TOCÁ OTRA VEZ':compact?'2 toques':'AUXILIO · 2 TOQUES'}</span><span className="sr-only" role="status">{armed?'Un toque más activa la cuenta regresiva.':''}</span></button>
}
export default function EmergencyHome({demo,onActivate,onConfirm,onNavigate,onPhoto,onLogin}:{demo:boolean,onActivate:()=>void,onConfirm:()=>void,onNavigate:(v:string)=>void,onPhoto:()=>void,onLogin:()=>void}){
 const shortcuts=[{view:'journal',title:'Grabar lo que veo',text:'Audio, descripción y guardados',icon:Mic},{view:'contacts',title:'Mis contactos',text:'Llamadas y mensajes de ayuda',icon:BookUser},{view:'plans',title:'Planes y pagos',text:'7 días de prueba · Google Play',icon:Wallet},{view:'privacy-center',title:'Privacidad',text:'Revisá quién ve tus datos',icon:ShieldCheck},{view:'sounds',title:'Sonidos',text:'Tonos nuevos, breves y suaves',icon:Volume2}];
 return <section className="emergency-home" aria-label="Acciones de seguridad"><div className="emergency-hero"><div><p className="eyebrow">TU SEGURIDAD, A MANO</p><h1>Cuando necesitás ayuda,<br/>tu SOS está acá.</h1><p>Dos toques consecutivos inician el aviso a tu círculo. Tenés cinco segundos para cancelarlo.</p><div className="emergency-state">{demo?'DEMOSTRACIÓN · No envía avisos ni llama a nadie':'Avisos a tu círculo · Requiere conexión y contactos registrados'}</div><button className="text-link" onClick={onConfirm}>Abrir la confirmación con un toque</button></div><SosButton onActivate={onActivate}/></div><div className="emergency-shortcuts">{shortcuts.map(s=><button key={s.view} onClick={()=>onNavigate(s.view)}><s.icon size={23}/><strong>{s.title}</strong><span>{s.text}</span></button>)}<button onClick={onPhoto}><Camera size={23}/><strong>Foto del entorno</strong><span>Capturá y elegí sus permisos</span></button></div><div className="emergency-secondary"><button className="button outline" onClick={()=>onNavigate('contacts')}><Phone size={18}/>Emergencias y policía</button>{demo&&<button className="button primary" onClick={onLogin}><UserRoundPlus size={18}/>Ingresar o crear mi cuenta</button>}</div></section>
}
