import {useEffect,useState} from 'react';
import {Capacitor} from '@capacitor/core';
import {SOUND_PROFILES,feedbackEnabled,setFeedbackEnabled,previewSound,testPhoneNotification,openSoundSettings,stopSound,previewVolume,setPreviewVolume} from './sounds';
export default function SoundSettings(){
 const [enabled,setEnabled]=useState(feedbackEnabled),[status,setStatus]=useState(''),[volume,setVolume]=useState(previewVolume);const android=Capacitor.getPlatform()==='android';
 useEffect(()=>()=>stopSound(),[]);
 async function act(work:()=>Promise<unknown>,message=''){try{await work();setStatus(message)}catch(e){setStatus(e instanceof Error?e.message:'No se pudo completar la prueba.')}}
 return <section className="sound-settings"><h3>Campanas suaves, sin sirenas.</h3><p>Renovamos los doce tonos. Escuchá cada uno antes de elegir los ajustes de tu teléfono.</p><label className="sound-volume"><span>Volumen de esta vista previa: {Math.round(volume*100)}%</span><input aria-label="Volumen de la vista previa" type="range" min="5" max="100" value={Math.round(volume*100)} onChange={e=>{const n=Number(e.target.value)/100;setVolume(n);setPreviewVolume(n)}}/></label><button className="button outline" onClick={()=>{stopSound();setStatus('Reproducción detenida.')}}>Detener sonido</button><div className="sound-grid">{SOUND_PROFILES.map(p=><article className="sound-card" key={p.kind}><strong>{p.label}</strong><small>{p.description}{!p.notification?' · Confirmación opcional de la app':''}</small><div><button className="button outline" type="button" onClick={()=>act(()=>previewSound(p.kind),'Escuchando: '+p.label)}>Escuchar</button>{android&&p.notification&&<><button className="button outline" type="button" onClick={()=>act(()=>testPhoneNotification(p.kind),'Prueba local en 2 segundos. No avisa a tu círculo.')}>Probar aviso</button><button className="text-link" type="button" onClick={()=>act(()=>openSoundSettings(p.kind))}>Elegir otro tono o silenciar en Android</button></>}</div></article>)}</div><label className="sound-feedback"><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);setFeedbackEnabled(e.target.checked)}}/> Sonidos opcionales al guardar y confirmar acciones</label><p>Los sonidos internos se pausan mientras grabás. El volumen de las notificaciones reales, su tono, el silencio y No molestar se controlan en Android; el deslizador solo ajusta esta vista previa y las confirmaciones internas.</p>{android?<button className="text-link" onClick={()=>act(()=>openSoundSettings())}>Abrir ajustes de notificaciones de Android</button>:<p>Cuando instales la versión Android podrás cambiar cada aviso desde los ajustes del teléfono.</p>}<p className="sound-play-status" role="status">{status}</p></section>
}
